# -*- coding: utf-8 -*-
"""longest_contig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jozgencSSVlt78cb9jh5Poz4EfgeA7bE
"""

from Bio import SeqIO
import sys

assembly = sys.argv[1]
output_file = sys.argv[2]
records = list(SeqIO.parse(assembly, "fasta"))
longest = max(records, key=lambda x: len(x.seq))
SeqIO.write(longest, output_file, "fasta")